version: '3.9'
services:  
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/test
    environment:
      NODE_ENV: test

  hero-webapp:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      NODE_ENV: prod